name: AristTpa
version: 1.0.0
main: me.vennlmao.aristpa.AristTpa
api-version: '1.21'
folia-supported: true
authors:
  - vennlmao

commands:
  tpa:
    description: Send a teleport request
    usage: /tpa <player>
  tpahere:
    description: Send a tpahere request
    usage: /tpahere <player>
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept [player]
  tpacancel:
    description: Cancel your outgoing teleport request
    usage: /tpacancel
  tpauto:
    description: Toggle auto-accept teleport requests
    usage: /tpauto
  tpatoggle:
    description: Toggle receiving tpa requests
    usage: /tpatoggle
  tpaheretoggle:
    description: Toggle receiving tpahere requests
    usage: /tpaheretoggle
